#------1.功能与环境-------
# 设置工作目录
# Set working directory
setwd("D:/NHANES")

# 加载必要包
# Load necessary packages
library(data.table)
library(dplyr)
library(survey)

# 复杂抽样设计的孤立初级抽样单元调整
# Adjustment for lonely primary sampling units in complex survey designs
options(survey.lonely.psu = "adjust")
options(survey.adjust.domain.lonely = TRUE)

#------2.数据导入与清洗---
# 导入数据，将所有空缺转为 NA
# Import data and convert all blanks to NA
raw_data <- data.table::fread(
  file = "data.csv",
  encoding = "UTF-8",
  na.strings = c("", "NA", "NaN", ".", "NULL", "null")
)

# 提取核心变量，严格使用 dplyr::select
# Extract core variables, strictly using dplyr::select
required_vars <- c(
  "Employment", "PIR", "Food.security", "Education", "Access.to.healthcare",
  "Health.insurance", "Housing.instability", "Marital.status", "SDoH",
  "sarcopenia_FNIH", "sdmvpsu", "sdmvstra", "Weight",
  "Age", "Sex", "Race_ethnicity", "Smoking_status", "Drinking_status",
  "Diabetes", "Hypertension", "Hyperlipidemia", "CVD", "CKD"
)

analysis_dat <- raw_data %>%
  dplyr::select(dplyr::all_of(required_vars)) %>%
  as.data.table()

# 剔除存在缺失值以及权重为 0 或缺失的行
# Remove rows with missing values and zero or missing weights
analysis_dat <- analysis_dat[complete.cases(analysis_dat) & !is.na(Weight) & Weight > 0]

# 协变量因子化，根据 Table 1 规范命名与分组顺序
# Factorize covariates based on standard naming and grouping order from Table 1
analysis_dat[, Sex_fac := factor(Sex, levels = c(0, 1), labels = c("Male", "Female"))]
analysis_dat[, Race_fac := factor(Race_ethnicity, levels = c(2, 1, 3, 4), labels = c("Non-Hispanic White", "Non-Hispanic Black", "Mexican American", "Other race/ethnicity"))]
analysis_dat[, Smoke_fac := factor(Smoking_status, levels = c(1, 2, 3), labels = c("Never", "Former", "Current"))]
analysis_dat[, Drink_fac := factor(Drinking_status, levels = c(1, 2, 3), labels = c("Never", "Former", "Current"))]
analysis_dat[, DM_fac := factor(Diabetes, levels = c(0, 1, 2), labels = c("No", "Borderline", "Yes"))]
analysis_dat[, HTN_fac := factor(Hypertension, levels = c(0, 1), labels = c("No", "Yes"))]
analysis_dat[, HLD_fac := factor(Hyperlipidemia, levels = c(0, 1), labels = c("No", "Yes"))]
analysis_dat[, CVD_fac := factor(CVD, levels = c(0, 1), labels = c("No", "Yes"))]
analysis_dat[, CKD_fac := factor(CKD, levels = c(0, 1), labels = c("No", "Yes"))]

# 单项 SDoH 变量转化为 0（有利）与 1（不利）的二分类因子
# Convert single SDoH variables into binary factors of 0 (favourable) and 1 (unfavourable)
analysis_dat[, emp_bin := factor(fcase(Employment == "Employed, student, or retired", 0L, Employment == "Unemployed", 1L, default = NA_integer_), levels = c(0, 1))]
analysis_dat[, pir_bin := factor(fcase(PIR == ">=3", 0L, PIR == "<3", 1L, default = NA_integer_), levels = c(0, 1))]
analysis_dat[, food_bin := factor(fcase(Food.security == "Full food security", 0L, Food.security %like% "Marginal", 1L, default = NA_integer_), levels = c(0, 1))]
analysis_dat[, edu_bin := factor(fcase(Education == "High school graduate or higher", 0L, Education == "Less than high school", 1L, default = NA_integer_), levels = c(0, 1))]
analysis_dat[, access_bin := factor(fcase(Access.to.healthcare %like% "At least one", 0L, Access.to.healthcare %like% "None or emergency", 1L, default = NA_integer_), levels = c(0, 1))]
analysis_dat[, ins_bin := factor(fcase(Health.insurance == "Private insurance", 0L, Health.insurance == "Government insurance or no insurance", 1L, default = NA_integer_), levels = c(0, 1))]
analysis_dat[, house_bin := factor(fcase(Housing.instability == "Own home", 0L, Housing.instability %like% "Rent home", 1L, default = NA_integer_), levels = c(0, 1))]
analysis_dat[, marital_bin := factor(fcase(Marital.status == "Married or living with a partner", 0L, Marital.status == "Not married nor living with a partner", 1L, default = NA_integer_), levels = c(0, 1))]

# 建立连续与多分类的累计 SDoH 变量
# Create continuous and categorical cumulative SDoH variables
analysis_dat[, cum_sdoh_score := fifelse(SDoH >= 6, 6L, as.integer(SDoH))]
analysis_dat[, cum_sdoh_cat := factor(cum_sdoh_score, levels = 0:6)]

# 再次清理重编码可能产生的缺失值
# Clean up potential missing values generated by recoding again
clean_vars <- c("emp_bin", "pir_bin", "food_bin", "edu_bin", "access_bin", "ins_bin", "house_bin", "marital_bin", "cum_sdoh_score", "cum_sdoh_cat")
analysis_dat <- analysis_dat[complete.cases(analysis_dat[, ..clean_vars])]

#------3.分析/建模---------
# 构建整体人群抽样设计与性别分层设计
# Build overall sampling design and sex-stratified designs
nhanes_design <- svydesign(ids = ~sdmvpsu, strata = ~sdmvstra, weights = ~Weight, nest = TRUE, data = analysis_dat)
female_design <- subset(nhanes_design, Sex_fac == "Female")
male_design <- subset(nhanes_design, Sex_fac == "Male")

# 初始化空数据框存储 Table 2 和 Figure 2 的结果
# Initialize empty data frames to store results for Table 2 and Figure 2
table2_results <- data.table()
figure2_results <- data.table()

# 定义模型协变量公式字符串
# Define formula strings for model covariates
covars_m1 <- "+ Age + Sex_fac + Race_fac"
covars_m2 <- "+ Age + Sex_fac + Race_fac + Smoke_fac + Drink_fac + DM_fac + HTN_fac + HLD_fac + CVD_fac + CKD_fac"
covars_strat <- "+ Age + Race_fac + Smoke_fac + Drink_fac + DM_fac + HTN_fac + HLD_fac + CVD_fac + CKD_fac"

# ----------------- Table 2 主分析计算循环 -----------------
# Loop for Table 2 main analysis computation
sdoh_list <- c("emp_bin", "pir_bin", "food_bin", "edu_bin", "access_bin", "ins_bin", "house_bin", "marital_bin")

for (var_name in sdoh_list) {
  form_crude <- as.formula(paste("sarcopenia_FNIH ~", var_name))
  form_m1 <- as.formula(paste("sarcopenia_FNIH ~", var_name, covars_m1))
  form_m2 <- as.formula(paste("sarcopenia_FNIH ~", var_name, covars_m2))
  
  fit_c <- svyglm(form_crude, design = nhanes_design, family = quasibinomial())
  fit_1 <- svyglm(form_m1, design = nhanes_design, family = quasibinomial())
  fit_2 <- svyglm(form_m2, design = nhanes_design, family = quasibinomial())
  
  # 直接提取比较组（1）的系数、标准误与 P 值
  # Directly extract coefficients, standard errors, and P values for the comparison group (1)
  term <- paste0(var_name, "1")
  
  coef_c <- summary(fit_c)$coefficients[term, ]
  or_c <- exp(coef_c[1])
  ci_c_low <- exp(coef_c[1] - 1.96 * coef_c[2])
  ci_c_high <- exp(coef_c[1] + 1.96 * coef_c[2])
  p_c <- coef_c[4]
  str_c <- sprintf("%.3f (%.3f, %.3f)", or_c, ci_c_low, ci_c_high)
  
  coef_1 <- summary(fit_1)$coefficients[term, ]
  or_1 <- exp(coef_1[1])
  ci_1_low <- exp(coef_1[1] - 1.96 * coef_1[2])
  ci_1_high <- exp(coef_1[1] + 1.96 * coef_1[2])
  p_1 <- coef_1[4]
  str_1 <- sprintf("%.3f (%.3f, %.3f)", or_1, ci_1_low, ci_1_high)
  
  coef_2 <- summary(fit_2)$coefficients[term, ]
  or_2 <- exp(coef_2[1])
  ci_2_low <- exp(coef_2[1] - 1.96 * coef_2[2])
  ci_2_high <- exp(coef_2[1] + 1.96 * coef_2[2])
  p_2 <- coef_2[4]
  str_2 <- sprintf("%.3f (%.3f, %.3f)", or_2, ci_2_low, ci_2_high)
  
  temp_row <- data.table(
    Variable = var_name,
    Crude_OR_95CI = str_c, Crude_P = p_c,
    Model1_OR_95CI = str_1, Model1_P = p_1,
    Model2_OR_95CI = str_2, Model2_P = p_2
  )
  table2_results <- rbind(table2_results, temp_row)
}

# ----------------- Figure 2 性别分层与交互分析计算循环 -----------------
# Loop for Figure 2 sex-stratified and interaction analysis computation
design_list <- list(Female = female_design, Male = male_design)

for (sex_name in names(design_list)) {
  current_design <- design_list[[sex_name]]
  
  form_cat <- as.formula(paste("sarcopenia_FNIH ~ cum_sdoh_cat", covars_strat))
  form_trend <- as.formula(paste("sarcopenia_FNIH ~ cum_sdoh_score", covars_strat))
  
  fit_cat <- svyglm(form_cat, design = current_design, family = quasibinomial())
  fit_trend <- svyglm(form_trend, design = current_design, family = quasibinomial())
  
  # 提取多分类等级 1 至 6 的结果
  # Extract results for categorical levels 1 to 6
  for (i in 1:6) {
    term <- paste0("cum_sdoh_cat", i)
    coef_cat <- summary(fit_cat)$coefficients[term, ]
    or_val <- exp(coef_cat[1])
    low_val <- exp(coef_cat[1] - 1.96 * coef_cat[2])
    high_val <- exp(coef_cat[1] + 1.96 * coef_cat[2])
    p_val <- coef_cat[4]
    
    str_val <- sprintf("%.3f (%.3f, %.3f)", or_val, low_val, high_val)
    
    temp_row <- data.table(
      Subgroup = sex_name,
      SDoH_Level = paste0("Level_", i),
      Adjusted_OR_95CI = str_val,
      Adjusted_P = p_val
    )
    figure2_results <- rbind(figure2_results, temp_row)
  }
  
  # 提取连续性趋势 P 值
  # Extract continuous trend P-value
  coef_trend <- summary(fit_trend)$coefficients["cum_sdoh_score", ]
  temp_trend <- data.table(
    Subgroup = sex_name,
    SDoH_Level = "P_for_trend",
    Adjusted_OR_95CI = "-",
    Adjusted_P = coef_trend[4]
  )
  figure2_results <- rbind(figure2_results, temp_trend)
}

# 计算基于总人群的性别交互作用 Wald 检验 P 值
# Calculate interaction Wald test P-value based on overall population
form_int <- as.formula(paste("sarcopenia_FNIH ~ cum_sdoh_cat * Sex_fac", covars_strat))
fit_int <- svyglm(form_int, design = nhanes_design, family = quasibinomial())
p_interaction <- survey::regTermTest(fit_int, ~cum_sdoh_cat:Sex_fac)$p[1,1]

temp_int <- data.table(
  Subgroup = "Interaction",
  SDoH_Level = "P_for_interaction",
  Adjusted_OR_95CI = "-",
  Adjusted_P = p_interaction
)
figure2_results <- rbind(figure2_results, temp_int)

#------4.可视化与导出------
# 对 P 值进行格式整理并导出
# Format P-values and export
format_p_val <- function(p) {
  if (is.na(p) || p == "-") return(p)
  p_num <- as.numeric(p)
  if (p_num < 0.001) return("<0.001") else return(sprintf("%.3f", p_num))
}

table2_results[, Crude_P := sapply(Crude_P, format_p_val)]
table2_results[, Model1_P := sapply(Model1_P, format_p_val)]
table2_results[, Model2_P := sapply(Model2_P, format_p_val)]

figure2_results[, Adjusted_P := sapply(Adjusted_P, format_p_val)]

# 优先使用 fwrite 保存，采用 UTF-8 BOM 确保 Excel 不乱码
# Prioritize saving with fwrite, using UTF-8 BOM to prevent garbled text in Excel
data.table::fwrite(table2_results, file = "Table 2.csv", bom = TRUE)
data.table::fwrite(figure2_results, file = "Figure 2.csv", bom = TRUE)